version = '2'

[run]
timeout = '5m'

[linters]
enable = [
  'asciicheck',
  'errorlint',
  'godot',
  'misspell',
  'nakedret',
  'nilerr',
  'nolintlint',
  'perfsprint',
  'usestdlibvars',
  'wastedassign'
]

[[linters.exclusions.rules]]
linters = [
  'perfsprint',
  'usestdlibvars',
  'errcheck'
]
path = '_test\.go'

[formatters]
enable = [
  'gofumpt',
  'goimports'
]
